version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: ruslan
      POSTGRES_DB: demo
    depends_on:
      - postgres-exporter
    networks:
      - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:pass123@localhost:5432/postgres?sslmode=disable"
    networks:
    - postgres

networks:
  postgres:
    name: postgres
    driver: bridge
