version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD=pass123
      POSTGRES_USER=postgres
      POSTGRES_DB=demo
    networks:
    - postgres  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME="postgresql://postgres:pass123@localhost:5432/postgres?sslmode=disable"
    networks:
    - postgres
    - postgres-prometheus
    
  prometheus:
    image: prom/prometheus
    volumes:
    - /path/to/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
    - postgres-prometheus
      
  grafana:
    image: grafana/grafana-enterprise:8.4.3-ubuntu
    ports:
      - 3000:3000
  
networks:
  postgres:
    name: postgres
    driver: bridge
  postgres-prometheus:
    name: postgres-prometheus
    driver: bridge